blueprint:
  name: Casambi Button Toggle and Dim
  description: Short press to toggle light, hold to dim (combines toggle and dimming functionality) - v1.2.2
  domain: automation
  input:
    unit_id:
      name: Unit ID
      description: The Casambi unit ID of your switch
      selector:
        number:
          mode: box
    button:
      name: Button Number
      description: Button number (0-based)
      default: 0
      selector:
        number:
          mode: box
    message_type:
      name: Message Type (Optional)
      description: Filter by message type. Leave empty to accept any
      default: ""
      selector:
        text:
    target_light:
      name: Target Light
      description: The light to control
      selector:
        entity:
          domain: light
    dimming_direction:
      name: Dimming Direction
      description: Direction to dim when holding the button
      default: toggle
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "up"
            - label: "Decrease Brightness"
              value: "down"
            - label: "Toggle Direction (if brightness > 50% dim down, otherwise dim up)"
              value: "toggle"
    dimming_step:
      name: Dimming Step
      description: How much to change brightness each step (0-255, will be converted to percentage)
      default: 25
      selector:
        number:
          min: 1
          max: 50
          mode: slider
    dimming_interval:
      name: Dimming Interval
      description: Milliseconds between each dimming step
      default: 200
      selector:
        number:
          min: 50
          max: 1000
          step: 50
          unit_of_measurement: ms
    button_state_helper:
      name: Button State Helper
      description: Input text helper to track button state (create one per button you want to control)
      selector:
        entity:
          domain: input_text
    debounce_time:
      name: Debounce Time
      description: Minimum seconds between toggle actions (prevents accidental double-triggers)
      default: 1
      selector:
        number:
          min: 0.5
          max: 5
          step: 0.5
          unit_of_measurement: seconds

mode: parallel  # Allow multiple instances
max: 3

variables:
  message_type: !input message_type
  target_light: !input target_light
  dimming_direction: !input dimming_direction
  dimming_step: !input dimming_step
  dimming_interval: !input dimming_interval
  button_state_helper: !input button_state_helper
  debounce_time: !input debounce_time

trigger:
  - platform: event
    event_type: casambi_bt_switch_event
    event_data:
      unit_id: !input unit_id
      button: !input button

condition:
  - condition: template
    value_template: >
      {% set message_type_filter = message_type | default('') %}
      {% set event_message_type = trigger.event.data.message_type | string %}
      {% set event_action = trigger.event.data.action %}
      {% set message_match = (message_type_filter == '') or (message_type_filter == event_message_type) %}
      
      {# Accept all relevant button events #}
      {{ message_match and event_action in ['button_press', 'button_release', 'button_hold', 'button_release_after_hold'] }}

action:
  - variables:
      event_action: "{{ trigger.event.data.action }}"
      current_state: "{{ states(button_state_helper) }}"
      is_holding: "{{ current_state == 'holding' }}"
      is_release_event: "{{ event_action in ['button_release', 'button_release_after_hold'] }}"
      
  - choose:
      # Handle button press - just track state
      - conditions:
          - condition: template
            value_template: "{{ event_action == 'button_press' }}"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: !input button_state_helper
            data:
              value: "pressed"
      
      # Handle normal button release (short press)
      - conditions:
          - condition: template
            value_template: "{{ event_action == 'button_release' and not is_holding }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input target_light
          - service: input_text.set_value
            target:
              entity_id: !input button_state_helper
            data:
              value: "idle"
      
      # Handle button release after hold
      - conditions:
          - condition: template
            value_template: "{{ event_action == 'button_release_after_hold' and is_holding }}"
        sequence:
          # Just reset the state, dimming already stopped when helper changed
          - service: input_text.set_value
            target:
              entity_id: !input button_state_helper
            data:
              value: "idle"
      
      # Handle any other release scenarios (including normal release while holding)
      - conditions:
          - condition: template
            value_template: "{{ event_action == 'button_release' and is_holding }}"
        sequence:
          # Reset state to stop dimming
          - service: input_text.set_value
            target:
              entity_id: !input button_state_helper
            data:
              value: "idle"
      
      # Handle button hold - update helper and start dimming loop
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.action == 'button_hold' }}"
        sequence:
          # Update button state to holding
          - service: input_text.set_value
            target:
              entity_id: !input button_state_helper
            data:
              value: "holding"
          
          # Determine direction based on settings and current brightness
          - variables:
              light_entity: !input target_light
              direction_setting: !input dimming_direction
              current_brightness: "{{ state_attr(light_entity, 'brightness') | int(0) }}"
              should_dim_up: "{{ direction_setting == 'up' or (direction_setting == 'toggle' and (states(light_entity) == 'off' or current_brightness <= 127)) }}"
          
          # Choose which dimming loop to execute based on direction
          - choose:
              # Dimming UP loop
              - conditions:
                  - condition: template
                    value_template: "{{ should_dim_up }}"
                sequence:
                  - repeat:
                      while:
                        - condition: and
                          conditions:
                            - condition: state
                              entity_id: !input button_state_helper
                              state: "holding"
                            - condition: template
                              value_template: >
                                {% set light = target_light %}
                                {% set brightness = state_attr(light, 'brightness') | int(0) %}
                                {{ states(light) == 'on' and brightness < 255 }}
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: !input target_light
                          data:
                            brightness_step_pct: "{{ (dimming_step | default(25) / 255 * 100) | round(1) }}"
                            transition: "{{ (dimming_interval | default(200)) / 1000 }}"
                        - delay:
                            milliseconds: !input dimming_interval
              
              # Dimming DOWN loop  
              - conditions:
                  - condition: template
                    value_template: "{{ not should_dim_up }}"
                sequence:
                  - repeat:
                      while:
                        - condition: and
                          conditions:
                            - condition: state
                              entity_id: !input button_state_helper
                              state: "holding"
                            - condition: template
                              value_template: >
                                {% set light = target_light %}
                                {% set brightness = state_attr(light, 'brightness') | int(0) %}
                                {{ states(light) == 'on' and brightness > 1 }}
                      sequence:
                        - variables:
                            current_brightness: "{{ state_attr(target_light, 'brightness') | int(255) }}"
                            # Use smaller steps when near minimum
                            step_pct: >
                              {% if current_brightness <= 16 %}
                                {{ ((current_brightness - 1) / 255 * 100) | abs }}
                              {% else %}
                                {{ (dimming_step | default(25) / 255 * 100) | round(1) }}
                              {% endif %}
                        - service: light.turn_on
                          target:
                            entity_id: !input target_light
                          data:
                            brightness_step_pct: "{{ -step_pct }}"
                            transition: "{{ (dimming_interval | default(200)) / 1000 }}"
                        - delay:
                            milliseconds: !input dimming_interval
          
          # Reset state if we hit the limits
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {% set brightness = state_attr(target_light, 'brightness') | int(0) %}
                      {{ brightness <= 3 or brightness >= 252 }}
                sequence:
                  - service: input_text.set_value
                    target:
                      entity_id: !input button_state_helper
                    data:
                      value: "idle"